<a href="https://colab.research.google.com/github/Aman78695/start_up_dashboard/blob/main/startup_dashboard_using_streamlit_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Cleaning and Preprocessing

In [3]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('/content/startup_funding.csv')

In [5]:
df

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
...,...,...,...,...,...,...,...,...,...,...
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [15]:
!pip install texthero

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting texthero
  Using cached texthero-1.1.0-py3-none-any.whl (24 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from texthero) (1.22.4)
Requirement already satisfied: scikit-learn>=0.22 in /usr/local/lib/python3.10/dist-packages (from texthero) (1.2.2)
Collecting spacy<3.0.0 (from texthero)
  Using cached spacy-2.3.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
Requirement already satisfied: tqdm>=4.3 in /usr/local/lib/python3.10/dist-packages (from texthero) (4.65.0)
Requirement already satisfied: nltk>=3.3 in /usr/local/lib/python3.10/dist-packages (from texthero) (3.8.1)
Requirement already satisfied: plotly>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from texthero) (5.13.1)
Requirement already satisfied: pandas>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from texthero) (1.5.3)
Requirement already satisfied: wordcloud>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from texthero) (1.8.2.2)
Collecting unidecode>=1.1.1 (from texthero)
  Using cached Unidecode-1.3.6-py3-none-any.whl (235 kB)
Collecting gensim<4.0,>=3.6.0 (from texthero)
  Using cached gensim-3.8.3.tar.gz (23.4 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: matplotlib>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from texthero) (3.7.1)
Requirement already satisfied: scipy>=0.18.1 in /usr/local/lib/python3.10/dist-packages (from gensim<4.0,>=3.6.0->texthero) (1.10.1)
Requirement already satisfied: six>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from gensim<4.0,>=3.6.0->texthero) (1.16.0)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from gensim<4.0,>=3.6.0->texthero) (6.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.0->texthero) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.0->texthero) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.0->texthero) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.0->texthero) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.0->texthero) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.0->texthero) (8.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.0->texthero) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.0->texthero) (2.8.2)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk>=3.3->texthero) (8.1.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk>=3.3->texthero) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk>=3.3->texthero) (2022.10.31)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.2->texthero) (2022.7.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=4.2.0->texthero) (8.2.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22->texthero) (3.1.0)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.0.0->texthero) (1.0.9)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.0.0->texthero) (2.0.7)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.0.0->texthero) (3.0.8)
Collecting thinc<7.5.0,>=7.4.1 (from spacy<3.0.0->texthero)
  Using cached thinc-7.4.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.0.0->texthero) (0.7.9)
Collecting wasabi<1.1.0,>=0.4.0 (from spacy<3.0.0->texthero)
  Using cached wasabi-0.10.1-py3-none-any.whl (26 kB)
Collecting srsly<1.1.0,>=1.0.2 (from spacy<3.0.0->texthero)
  Using cached srsly-1.0.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (209 kB)
Collecting catalogue<1.1.0,>=0.0.7 (from spacy<3.0.0->texthero)
  Using cached catalogue-1.0.2-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.0.0->texthero) (67.7.2)
Collecting plac<1.2.0,>=0.9.6 (from spacy<3.0.0->texthero)
  Using cached plac-1.1.3-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.0.0->texthero) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.0.0->texthero) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.0.0->texthero) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.0.0->texthero) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.0.0->texthero) (3.4)
Building wheels for collected packages: gensim
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for gensim (setup.py) ... error
  ERROR: Failed building wheel for gensim
  Running setup.py clean for gensim
Failed to build gensim
ERROR: Could not build wheels for gensim, which is required to install pyproject.toml-based projects

In [10]:
!pip install -U spacy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: spacy in /usr/local/lib/python3.10/dist-packages (3.5.2)
Collecting spacy
  Downloading spacy-3.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 36.5 MB/s eta 0:00:00
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.0.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.0.9)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.0.7)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.0.8)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /usr/local/lib/python3.10/dist-packages (from spacy) (8.1.9)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.1.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.4.6)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.0.8)
Requirement already satisfied: typer<0.8.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (0.7.0)
Requirement already satisfied: pathy>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (0.10.1)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy) (6.3.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (4.65.0)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.22.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.27.1)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.10.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy) (67.7.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (23.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4->spacy) (4.5.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy) (0.7.9)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy) (0.0.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.8.0,>=0.3.0->spacy) (8.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy) (2.1.2)
Installing collected packages: spacy
  Attempting uninstall: spacy
    Found existing installation: spacy 3.5.2
    Uninstalling spacy-3.5.2:
      Successfully uninstalled spacy-3.5.2
Successfully installed spacy-3.5.3

In [14]:
import warnings

warnings.filterwarnings(action="ignore", category=UserWarning, module="gensim")

In [17]:
!pip install texthero==1.0.5

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting texthero==1.0.5
  Downloading texthero-1.0.5-py3-none-any.whl (12 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from texthero==1.0.5) (3.8.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from texthero==1.0.5) (1.2.2)
Collecting plotly-express (from texthero==1.0.5)
  Downloading plotly_express-0.4.1-py2.py3-none-any.whl (2.9 kB)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->texthero==1.0.5) (8.1.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->texthero==1.0.5) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk->texthero==1.0.5) (2022.10.31)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk->texthero==1.0.5) (4.65.0)
Requirement already satisfied: pandas>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from plotly-express->texthero==1.0.5) (1.5.3)
Requirement already satisfied: plotly>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from plotly-express->texthero==1.0.5) (5.13.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from plotly-express->texthero==1.0.5) (0.13.5)
Requirement already satisfied: scipy>=0.18 in /usr/local/lib/python3.10/dist-packages (from plotly-express->texthero==1.0.5) (1.10.1)
Requirement already satisfied: patsy>=0.5 in /usr/local/lib/python3.10/dist-packages (from plotly-express->texthero==1.0.5) (0.5.3)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.10/dist-packages (from plotly-express->texthero==1.0.5) (1.22.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->texthero==1.0.5) (3.1.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.20.0->plotly-express->texthero==1.0.5) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.20.0->plotly-express->texthero==1.0.5) (2022.7.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5->plotly-express->texthero==1.0.5) (1.16.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=4.1.0->plotly-express->texthero==1.0.5) (8.2.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->plotly-express->texthero==1.0.5) (23.1)
Installing collected packages: plotly-express, texthero
Successfully installed plotly-express-0.4.1 texthero-1.0.5

In [19]:
!pip install unidecode

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting unidecode
  Using cached Unidecode-1.3.6-py3-none-any.whl (235 kB)
Installing collected packages: unidecode
Successfully installed unidecode-1.3.6

In [20]:
import texthero as hero

In [22]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [23]:
df['Startup Name']=hero.clean(df['Startup Name'])

/usr/local/lib/python3.10/dist-packages/texthero/preprocessing.py:81: FutureWarning: The default value of regex will change from True to False in a future version.
  return input.str.replace(pat, '')

In [24]:
df

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,byju',E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https www wealthbucket,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
...,...,...,...,...,...,...,...,...,...,...
3039,3040,29/01/2015,printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,29/01/2015,graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30/01/2015,mad street den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,30/01/2015,simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,31/01/2015,couponmachine,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [ ]:
sorted(list(df['Startup Name'].unique()))

In [29]:
df['Investors Name']=df['Investors Name'].fillna('undisclosed')

In [32]:
df[df['Investors Name'].str.contains('Sequoia Capital India')].head()[['Date dd/mm/yyyy','Startup Name','Investors Name','Amount in USD']]

,Date dd/mm/yyyy,Startup Name,Investors Name,Amount in USD
2,09/01/2020,mamaearth,Sequoia Capital India,"1,83,58,860"
68,11/07/2019,moglix,"Composite Capital Management, Sequoia Capital ...","6,00,00,000"
149,12/10/2018,blackbuck,Sequoia Capital India,"1,46,80,000"
166,02/08/2018,samosa labs,Xiaomi and Sequoia Capital India,"70,00,000"
172,08/08/2018,metro bikes,"Sequoia Capital India Advisors, Accel Partners...","1,22,00,000"

In [48]:
df['Amount in USD']=df['Amount in USD'].str.replace(',','')
df['Amount in USD'].fillna('0',inplace=True)
df['Amount in USD']=df['Amount in USD'].str.replace('undisclosed','0')
df['Amount in USD']=df['Amount in USD'].str.replace('unknown','0')
df['Amount in USD']=df['Amount in USD'].str.replace('Undisclosed','0')
df['Amount in USD']=df['Amount in USD'].str.replace('14342000+','0')
df['Amount in USD']=df['Amount in USD'].str.replace('NaN','0')
df=df[df['Amount in USD'].str.isdigit()]

<ipython-input-48-3693b5ce44ba>:6: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Amount in USD']=df['Amount in USD'].str.replace('14342000+','0')

In [49]:
df['Amount in USD']=df['Amount in USD'].astype('float')

<ipython-input-49-da69b764773f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Amount in USD']=df['Amount in USD'].astype('float')

In [50]:
df[df['Investors Name'].str.contains('Sequoia Capital India')].groupby('Startup Name')['Amount in USD'].sum().sort_values(ascending=False).head()

Startup Name
oyo rooms    500000000.0
dhruva        80000000.0
moglix        60000000.0
freshdesk     55000000.0
newshunt      40000000.0
Name: Amount in USD, dtype: float64

In [ ]:
verical_series = df[df['Investors Name'].str.contains(investor)].groupby('vertical')['amount'].sum()

## app.py run on pycharm and streamlit was used for web development

In [ ]:
!pip install streamlit

In [ ]:
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('startup_funding.csv')
df['Investors Name']=df['Investors Name'].fillna('undisclosed')
df['Amount in USD']=df['Amount in USD'].str.replace(',','')
df['Amount in USD'].fillna('0',inplace=True)
df['Amount in USD']=df['Amount in USD'].str.replace('undisclosed','0')
df['Amount in USD']=df['Amount in USD'].str.replace('unknown','0')
df['Amount in USD']=df['Amount in USD'].str.replace('Undisclosed','0')
df['Amount in USD']=df['Amount in USD'].str.replace('14342000+','0')
df['Amount in USD']=df['Amount in USD'].str.replace('NaN','0')
df=df[df['Amount in USD'].str.isdigit()]
df['Amount in USD']=df['Amount in USD'].astype('float')
def investor_name(investor):
    st.title(investor)
    #latest investment by date
    st.subheader('latest_investment')
    investor_latest=df[df['Investors Name'].str.contains(investor)].head()[
        ['Date dd/mm/yyyy', 'Startup Name', 'Investors Name', 'Amount in USD']]
    st.dataframe(investor_latest)
    #big 5 investment
    st.subheader('big_5_investment')
    investment_big=df[df['Investors Name'].str.contains('investor')].groupby('Startup Name')['Amount in USD'].sum().sort_values(ascending=False).head()

    st.dataframe(investment_big)

    #vertical invested on
    verical_series = df[df['Investors Name'].str.contains(investor)].groupby('Industry Vertical')['Amount in USD'].sum()

    st.subheader('Sectors invested in')
    fig1, ax1 = plt.subplots()
    ax1.pie(verical_series, labels=verical_series.index, autopct="%0.01f%%")

    st.pyplot(fig1)


st.sidebar.title('Startup Investmont Analysis')
option=st.sidebar.selectbox('select one',['overall analysis','start up','investor'])

if option=='overall analysis':
    st.title('overall analysis')
elif option=='start up':
    st.sidebar.selectbox('select one', sorted(list(df['Startup Name'].unique())))
    st.sidebar.button('click for analysis')
    st.title('start up analysis')
else:
    name=st.sidebar.selectbox('select one', sorted(list(df['Investors Name'].unique())))
    btn2=st.sidebar.button('click for analysis')
    if btn2:
        investor_name(name)